[AutoGenerated]
moduleMatches = 0x6267BFD0
.origin = codecave








	.align 4
_94406c74bd2870f3_LCPI0_0:
	.int	0x00000000
_94406c74bd2870f3_LCPI0_1:
	.int	0x3f800000
_94406c74bd2870f3_LCPI0_2:
	.int	0x3e800000
_94406c74bd2870f3_LCPI0_3:
	.int	0xbf800000
_94406c74bd2870f3_LCPI0_4:
	.int	0x40000000
_94406c74bd2870f3_LCPI0_5:
	.int	0xc0000000
	.align 4
_Z20calculateNewRotationv:
_94406c74bd2870f3_Lfunc_begin0:
	stwu r1, -48(r1)
	lis r3, oldTargetPosX@ha
	lfs f3, oldTargetPosX@l(r3)
	lis r3, oldCamPosX@ha
	lfs f0, oldCamPosX@l(r3)
	lis r3, oldTargetPosY@ha
	lfs f4, oldTargetPosY@l(r3)
	lis r3, oldCamPosY@ha
	lfs f2, oldCamPosY@l(r3)
	lis r3, oldTargetPosZ@ha
	lfs f5, oldTargetPosZ@l(r3)
	lis r3, oldCamPosZ@ha
	lfs f1, oldCamPosZ@l(r3)
	fsubs f3, f3, f0
	fsubs f4, f4, f2
	fmuls f6, f3, f4
	fsubs f5, f5, f1
	fmuls f6, f6, f5
	fsqrts f6, f6
	lis r3, _94406c74bd2870f3_LCPI0_0@ha
	fdivs f7, f3, f6
	stfd f30, 32(r1)
	stfd f31, 40(r1)
	stfd f27, 8(r1)
	stfd f28, 16(r1)
	stfd f29, 24(r1)
	fdivs f8, f4, f6
	fdivs f3, f5, f6
	lfs f6, _94406c74bd2870f3_LCPI0_0@l(r3)
	lis r3, _94406c74bd2870f3_LCPI0_1@ha
	lfs f11, _94406c74bd2870f3_LCPI0_1@l(r3)
	lis r3, _94406c74bd2870f3_LCPI0_2@ha
	fmuls f4, f8, f6
	fmuls f9, f7, f8
	fmuls f5, f3, f9
	fmuls f4, f3, f4
	fmuls f12, f3, f6
	fsqrts f10, f5
	fdivs f5, f4, f10
	fmuls f12, f7, f12
	fmuls f4, f9, f6
	fmuls f13, f12, f6
	fmuls f12, f3, f5
	fdivs f9, f4, f10
	lfs f4, _94406c74bd2870f3_LCPI0_2@l(r3)
	fmuls f12, f7, f12
	fmuls f12, f9, f12
	fadds f31, f5, f12
	fsubs f30, f5, f12
	fadds f31, f3, f31
	fsubs f30, f30, f3
	fneg f28, f5
	fsubs f27, f12, f5
	fadds f31, f31, f11
	fadds f30, f30, f11
	fmuls f29, f31, f4
	fmuls f31, f30, f4
	fsubs f30, f27, f3
	fsubs f12, f28, f12
	fcmpu cr0, f29, f6
	fadds f30, f30, f11
	fadds f28, f3, f12
	fmr f12, f6
	blt	cr0, _94406c74bd2870f3_LBB0_2
	fmr f12, f29
_94406c74bd2870f3_LBB0_2:
	fdivs f10, f13, f10
	fcmpu cr0, f31, f6
	fadds f13, f28, f11
	fmuls f30, f30, f4
	fmr f11, f6
	blt	cr0, _94406c74bd2870f3_LBB0_4
	fmr f11, f31
_94406c74bd2870f3_LBB0_4:
	fcmpu cr0, f30, f6
	fmuls f31, f8, f9
	fmuls f29, f7, f10
	fmuls f4, f13, f4
	fmr f13, f6
	blt	cr0, _94406c74bd2870f3_LBB0_6
	fmr f13, f30
_94406c74bd2870f3_LBB0_6:
	fcmpu cr0, f4, f6
	fmuls f31, f3, f31
	fmuls f30, f8, f29
	blt	cr0, _94406c74bd2870f3_LBB0_8
	fmr f6, f4
_94406c74bd2870f3_LBB0_8:
	fsqrts f3, f12
	fsqrts f4, f11
	fcmpu cr7, f3, f4
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	fmuls f11, f10, f31
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	fmuls f12, f5, f30
	fsqrts f5, f13
	fsqrts f6, f6
	bne	cr0, _94406c74bd2870f3_LBB0_16
	fcmpu cr7, f3, f5
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_16
	fcmpu cr7, f3, f6
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_16
	lis r3, _94406c74bd2870f3_LCPI0_0@ha
	lfs f13, _94406c74bd2870f3_LCPI0_0@l(r3)
	fsubs f8, f8, f12
	fcmpu cr7, f8, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_13
	fneg f4, f4
_94406c74bd2870f3_LBB0_13:
	fsubs f7, f9, f7
	fcmpu cr7, f7, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_15
	fneg f5, f5
_94406c74bd2870f3_LBB0_15:
	fsubs f7, f11, f10
	b _94406c74bd2870f3_LBB0_32
_94406c74bd2870f3_LBB0_16:
	fcmpu cr7, f4, f3
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_24
	fcmpu cr7, f4, f5
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_24
	fcmpu cr7, f4, f6
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_24
	lis r3, _94406c74bd2870f3_LCPI0_0@ha
	lfs f13, _94406c74bd2870f3_LCPI0_0@l(r3)
	fsubs f8, f8, f12
	fcmpu cr7, f8, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_21
	fneg f3, f3
_94406c74bd2870f3_LBB0_21:
	fadds f8, f10, f11
	fcmpu cr7, f8, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_23
	fneg f5, f5
_94406c74bd2870f3_LBB0_23:
	fadds f7, f7, f9
	b _94406c74bd2870f3_LBB0_32
_94406c74bd2870f3_LBB0_24:
	fcmpu cr7, f5, f3
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_35
	fcmpu cr7, f5, f4
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_35
	fcmpu cr7, f5, f6
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_35
	lis r3, _94406c74bd2870f3_LCPI0_0@ha
	lfs f13, _94406c74bd2870f3_LCPI0_0@l(r3)
	fsubs f7, f9, f7
	fcmpu cr7, f7, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_29
	fneg f3, f3
_94406c74bd2870f3_LBB0_29:
	fadds f7, f10, f11
	fcmpu cr7, f7, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_31
	fneg f4, f4
_94406c74bd2870f3_LBB0_31:
	fadds f7, f8, f12
_94406c74bd2870f3_LBB0_32:
	fcmpu cr7, f7, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_34
	fneg f6, f6
_94406c74bd2870f3_LBB0_34:
	fmuls f7, f4, f3
	fmuls f7, f5, f7
	fmuls f7, f6, f7
	fsqrts f10, f7
	lis r4, headsetQuaternionZ@ha
	lis r6, headsetQuaternionX@ha
	fdivs f8, f3, f10
	lis r3, headsetQuaternionW@ha
	lis r5, headsetQuaternionY@ha
	lfs f11, headsetQuaternionX@l(r6)
	lis r6, distanceSetting@ha
	lis r7, _94406c74bd2870f3_LCPI0_3@ha
	lis r8, _94406c74bd2870f3_LCPI0_4@ha
	lfd f30, 32(r1)
	lfd f29, 24(r1)
	lfd f28, 16(r1)
	lfd f27, 8(r1)
	fdivs f9, f4, f10
	lfs f4, headsetQuaternionW@l(r3)
	lis r3, newTargetPosX@ha
	fdivs f7, f5, f10
	lfs f5, _94406c74bd2870f3_LCPI0_3@l(r7)
	fdivs f3, f6, f10
	lfs f10, headsetQuaternionZ@l(r4)
	lis r4, newTargetPosY@ha
	lfs f6, headsetQuaternionY@l(r5)
	lis r5, _94406c74bd2870f3_LCPI0_5@ha
	fneg f13, f9
	fmuls f12, f9, f10
	fmuls f31, f11, f13
	fmadds f12, f8, f4, f12
	fmadds f31, f8, f6, f31
	fneg f8, f8
	fmuls f9, f9, f4
	fmuls f13, f6, f13
	fmadds f9, f8, f10, f9
	fmadds f8, f8, f11, f13
	fneg f13, f7
	fmadds f12, f13, f6, f12
	fmadds f9, f7, f11, f9
	fmadds f7, f7, f4, f31
	fmadds f9, f3, f6, f9
	fmadds f8, f13, f10, f8
	lfs f13, distanceSetting@l(r6)
	fmadds f7, f3, f10, f7
	fnmadds f10, f3, f11, f12
	fmadds f4, f3, f4, f8
	fmuls f8, f9, f10
	fmadds f8, f7, f4, f8
	fmadds f3, f3, f11, f12
	fadds f8, f8, f8
	fmuls f12, f3, f4
	lfs f31, _94406c74bd2870f3_LCPI0_5@l(r5)
	lis r5, newCamPosY@ha
	fmadds f10, f8, f13, f2
	lfs f11, newTargetPosY@l(r4)
	fmadds f12, f9, f7, f12
	stfs f10, newCamPosY@l(r5)
	lis r5, newCamRotX@ha
	lfs f10, newTargetPosX@l(r3)
	fadds f12, f12, f12
	stfs f12, newCamRotX@l(r5)
	lis r5, newTargetPosZ@ha
	lfs f12, newTargetPosZ@l(r5)
	fmuls f11, f11, f11
	fmadds f10, f10, f10, f11
	fmuls f11, f7, f7
	fmuls f7, f3, f7
	fmadds f7, f9, f4, f7
	fmadds f10, f12, f12, f10
	fmuls f7, f7, f31
	fsqrts f10, f10
	fmadds f9, f7, f10, f0
	lfs f6, _94406c74bd2870f3_LCPI0_4@l(r8)
	fmadds f11, f3, f3, f11
	stfs f9, newTargetPosX@l(r3)
	fneg f9, f8
	fmadds f2, f9, f10, f2
	stfs f2, newTargetPosY@l(r4)
	fmuls f2, f4, f4
	fmadds f2, f3, f3, f2
	fneg f4, f7
	lis r3, newCamPosX@ha
	fmadds f3, f2, f6, f5
	fnmadds f2, f2, f6, f5
	fmadds f0, f4, f13, f0
	lis r6, newCamRotY@ha
	fmadds f11, f11, f6, f5
	lis r4, newCamPosZ@ha
	fmadds f2, f2, f10, f1
	fmadds f1, f3, f13, f1
	stfs f0, newCamPosX@l(r3)
	lis r3, newCamRotZ@ha
	stfs f11, newCamRotY@l(r6)
	stfs f2, newTargetPosZ@l(r5)
	stfs f1, newCamPosZ@l(r4)
	stfs f8, newCamRotZ@l(r3)
	lfd f31, 40(r1)
	addi r1, r1, 48
	blr
_94406c74bd2870f3_LBB0_35:
	fcmpu cr7, f6, f3
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_34
	fcmpu cr7, f6, f4
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_34
	fcmpu cr7, f6, f5
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_34
	lis r3, _94406c74bd2870f3_LCPI0_0@ha
	lfs f13, _94406c74bd2870f3_LCPI0_0@l(r3)
	fsubs f10, f11, f10
	fcmpu cr7, f10, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_40
	fneg f3, f3
_94406c74bd2870f3_LBB0_40:
	fadds f7, f7, f9
	fcmpu cr7, f7, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_42
	fneg f4, f4
_94406c74bd2870f3_LBB0_42:
	fadds f7, f8, f12
	fcmpu cr7, f7, f13
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB0_34
	fneg f5, f5
	b _94406c74bd2870f3_LBB0_34
_94406c74bd2870f3_Lfunc_end0:

	.align 4
oldTargetPosX:
	.int	0x3efd6fdb

	.align 4
oldTargetPosY:
	.int	0x3e4cd218

	.align 4
oldTargetPosZ:
	.int	0x3f0cb1ee

	.align 4
oldCamPosX:
	.int	0x3a126197

	.align 4
oldCamPosY:
	.int	0x3b8418ff

	.align 4
oldCamPosZ:
	.int	0x3d039c01

	.align 4
headsetQuaternionX:
	.int	0x3d03d9a9

	.align 4
headsetQuaternionY:
	.int	0x3d1d9b1b

	.align 4
headsetQuaternionZ:
	.int	0x3d0d1c7e

	.align 4
headsetQuaternionW:
	.int	0x3eb26aef

	.align 4
headsetPositionX:
	.int	0x3e9fe5c9

	.align 4
headsetPositionY:
	.int	0x3f5930be

	.align 4
headsetPositionZ:
	.int	0x3f59359b

	.align 4
newTargetPosX:
	.int	0x00000000

	.align 4
newTargetPosY:
	.int	0x00000000

	.align 4
newTargetPosZ:
	.int	0x00000000

	.align 4
newCamPosX:
	.int	0x00000000

	.align 4
newCamPosY:
	.int	0x00000000

	.align 4
newCamPosZ:
	.int	0x00000000

	.align 4
newCamRotX:
	.int	0x00000000

	.align 4
newCamRotY:
	.int	0x00000000

	.align 4
newCamRotZ:
	.int	0x00000000

	.align 4
distanceSetting:
	.int	0x3f800000


; --- Address Patches ---
0x023F90E0 = nop
0x101E55F8 = .float 3.0
0x10416BF0 = .int 0x00000000
0x02E1905C = li r3, 0
