[AutoGenerated]
moduleMatches = 0x6267BFD0
.origin = codecave








	.align 4
_94406c74bd2870f3_LCPI0_0:
	.int	0x3f000000
	.align 4
_Z5sqrtff:
_94406c74bd2870f3_Lfunc_begin0:
	lis r3, _94406c74bd2870f3_LCPI0_0@ha
	lfs f2, _94406c74bd2870f3_LCPI0_0@l(r3)
	fdivs f0, f1, f1
	fadds f0, f0, f1
	fmuls f0, f0, f2
	fdivs f3, f1, f0
	fadds f0, f0, f3
	fmuls f0, f0, f2
	fdivs f3, f1, f0
	fadds f0, f0, f3
	fmuls f0, f0, f2
	fdivs f3, f1, f0
	fadds f0, f0, f3
	fmuls f0, f0, f2
	fdivs f3, f1, f0
	fadds f0, f0, f3
	fmuls f0, f0, f2
	fdivs f3, f1, f0
	fadds f0, f0, f3
	fmuls f0, f0, f2
	fdivs f1, f1, f0
	fadds f0, f0, f1
	fmuls f1, f0, f2
	blr
_94406c74bd2870f3_Lfunc_end0:

	.align 4
_94406c74bd2870f3_LCPI1_0:
	.int	0x00000000
_94406c74bd2870f3_LCPI1_1:
	.int	0x3f800000
_94406c74bd2870f3_LCPI1_2:
	.int	0x3e800000
_94406c74bd2870f3_LCPI1_3:
	.int	0xbf800000
_94406c74bd2870f3_LCPI1_4:
	.int	0x40000000
_94406c74bd2870f3_LCPI1_5:
	.int	0xc0000000
	.align 4
_Z20calculateNewRotationv:
_94406c74bd2870f3_Lfunc_begin1:
	mflr r0
	stwu r1, -128(r1)
	stw r0, 132(r1)
	lis r3, oldTargetPosX@ha
	lfs f0, oldTargetPosX@l(r3)
	lis r3, oldCamPosX@ha
	stfd f27, 88(r1)
	lfs f27, oldCamPosX@l(r3)
	lis r3, oldTargetPosY@ha
	lfs f1, oldTargetPosY@l(r3)
	lis r3, oldCamPosY@ha
	stfd f26, 80(r1)
	lfs f26, oldCamPosY@l(r3)
	lis r3, oldTargetPosZ@ha
	lfs f2, oldTargetPosZ@l(r3)
	lis r3, oldCamPosZ@ha
	stfd f25, 72(r1)
	lfs f25, oldCamPosZ@l(r3)
	stfd f30, 112(r1)
	fsubs f30, f1, f26
	stfd f31, 120(r1)
	fsubs f31, f0, f27
	stfd f29, 104(r1)
	fsubs f29, f2, f25
	fmuls f0, f31, f30
	fmuls f1, f0, f29
	stw r28, 8(r1)
	stw r29, 12(r1)
	stw r30, 16(r1)
	stfd f19, 24(r1)
	stfd f20, 32(r1)
	stfd f21, 40(r1)
	stfd f22, 48(r1)
	stfd f23, 56(r1)
	stfd f24, 64(r1)
	stfd f28, 96(r1)
	bl _Z5sqrtff
	lis r3, _94406c74bd2870f3_LCPI1_0@ha
	lfs f28, _94406c74bd2870f3_LCPI1_0@l(r3)
	fdivs f24, f31, f1
	fdivs f23, f30, f1
	fdivs f31, f29, f1
	fmuls f1, f23, f28
	fmuls f2, f31, f28
	fmuls f0, f24, f23
	fmuls f22, f31, f1
	fmuls f1, f24, f2
	fmuls f30, f1, f28
	fmuls f1, f31, f0
	fmuls f29, f0, f28
	bl _Z5sqrtff
	fdivs f2, f22, f1
	lis r3, _94406c74bd2870f3_LCPI1_1@ha
	lfs f4, _94406c74bd2870f3_LCPI1_1@l(r3)
	lis r3, _94406c74bd2870f3_LCPI1_2@ha
	lfs f3, _94406c74bd2870f3_LCPI1_2@l(r3)
	fmuls f0, f31, f2
	fdivs f22, f29, f1
	fmuls f0, f24, f0
	fmuls f0, f22, f0
	fadds f5, f2, f0
	fsubs f6, f2, f0
	fadds f5, f31, f5
	fsubs f6, f6, f31
	fneg f8, f2
	fsubs f9, f0, f2
	fadds f5, f5, f4
	fadds f6, f6, f4
	fmuls f7, f5, f3
	fmuls f5, f6, f3
	fsubs f6, f9, f31
	fsubs f0, f8, f0
	fcmpu cr0, f7, f28
	fadds f6, f6, f4
	fadds f8, f31, f0
	fmr f0, f28
	blt	cr0, _94406c74bd2870f3_LBB1_2
	fmr f0, f7
_94406c74bd2870f3_LBB1_2:
	fdivs f21, f30, f1
	fcmpu cr0, f5, f28
	fadds f4, f8, f4
	fmuls f1, f6, f3
	fmr f30, f28
	blt	cr0, _94406c74bd2870f3_LBB1_4
	fmr f30, f5
_94406c74bd2870f3_LBB1_4:
	fcmpu cr0, f1, f28
	fmuls f5, f23, f22
	fmuls f6, f24, f21
	fmuls f3, f4, f3
	fmr f29, f28
	blt	cr0, _94406c74bd2870f3_LBB1_6
	fmr f29, f1
_94406c74bd2870f3_LBB1_6:
	fcmpu cr0, f3, f28
	fmuls f1, f31, f5
	fmuls f4, f23, f6
	blt	cr0, _94406c74bd2870f3_LBB1_8
	fmr f28, f3
_94406c74bd2870f3_LBB1_8:
	fmuls f20, f21, f1
	fmr f1, f0
	fmuls f19, f2, f4
	bl _Z5sqrtff
	fmr f31, f1
	fmr f1, f30
	bl _Z5sqrtff
	fmr f30, f1
	fmr f1, f29
	bl _Z5sqrtff
	fmr f29, f1
	fmr f1, f28
	bl _Z5sqrtff
	fcmpu cr7, f31, f30
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	fmr f28, f1
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_16
	fcmpu cr7, f31, f29
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_16
	fcmpu cr7, f31, f28
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_16
	lis r3, _94406c74bd2870f3_LCPI1_0@ha
	lfs f0, _94406c74bd2870f3_LCPI1_0@l(r3)
	fsubs f1, f23, f19
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_13
	fneg f30, f30
_94406c74bd2870f3_LBB1_13:
	fsubs f1, f22, f24
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_15
	fneg f29, f29
_94406c74bd2870f3_LBB1_15:
	fsubs f1, f20, f21
	b _94406c74bd2870f3_LBB1_32
_94406c74bd2870f3_LBB1_16:
	fcmpu cr7, f30, f31
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_24
	fcmpu cr7, f30, f29
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_24
	fcmpu cr7, f30, f28
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_24
	lis r3, _94406c74bd2870f3_LCPI1_0@ha
	lfs f0, _94406c74bd2870f3_LCPI1_0@l(r3)
	fsubs f1, f23, f19
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_21
	fneg f31, f31
_94406c74bd2870f3_LBB1_21:
	fadds f1, f21, f20
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_23
	fneg f29, f29
_94406c74bd2870f3_LBB1_23:
	fadds f1, f24, f22
	b _94406c74bd2870f3_LBB1_32
_94406c74bd2870f3_LBB1_24:
	fcmpu cr7, f29, f31
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_35
	fcmpu cr7, f29, f30
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_35
	fcmpu cr7, f29, f28
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_35
	lis r3, _94406c74bd2870f3_LCPI1_0@ha
	lfs f0, _94406c74bd2870f3_LCPI1_0@l(r3)
	fsubs f1, f22, f24
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_29
	fneg f31, f31
_94406c74bd2870f3_LBB1_29:
	fadds f1, f21, f20
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_31
	fneg f30, f30
_94406c74bd2870f3_LBB1_31:
	fadds f1, f23, f19
_94406c74bd2870f3_LBB1_32:
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_34
	fneg f28, f28
_94406c74bd2870f3_LBB1_34:
	fmuls f0, f30, f31
	fmuls f0, f29, f0
	fmuls f1, f28, f0
	bl _Z5sqrtff
	lis r3, headsetQuaternionW@ha
	fdivs f6, f31, f1
	lis r30, newTargetPosY@ha
	lis r29, newTargetPosX@ha
	lfs f9, newTargetPosY@l(r30)
	lis r28, newTargetPosZ@ha
	lfs f8, newTargetPosX@l(r29)
	fdivs f7, f30, f1
	fdivs f3, f29, f1
	fdivs f0, f28, f1
	lfs f1, headsetQuaternionW@l(r3)
	lis r3, headsetQuaternionZ@ha
	lfs f2, headsetQuaternionZ@l(r3)
	lis r3, headsetQuaternionY@ha
	lfs f5, headsetQuaternionY@l(r3)
	lis r3, headsetQuaternionX@ha
	lfs f4, headsetQuaternionX@l(r3)
	lis r3, _94406c74bd2870f3_LCPI1_3@ha
	fneg f10, f7
	fmuls f11, f7, f2
	fmuls f12, f4, f10
	fmadds f11, f6, f1, f11
	fmadds f12, f6, f5, f12
	fneg f6, f6
	fmuls f7, f7, f1
	fmuls f10, f5, f10
	fmadds f7, f6, f2, f7
	fmadds f6, f6, f4, f10
	fmadds f7, f3, f4, f7
	fmadds f10, f3, f1, f12
	fneg f3, f3
	fmadds f11, f3, f5, f11
	fmadds f3, f3, f2, f6
	fmuls f9, f9, f9
	fmadds f2, f0, f2, f10
	fmadds f1, f0, f1, f3
	fmadds f3, f0, f4, f11
	fmadds f8, f8, f8, f9
	lfs f9, _94406c74bd2870f3_LCPI1_3@l(r3)
	lis r3, _94406c74bd2870f3_LCPI1_4@ha
	fmadds f5, f0, f5, f7
	fnmadds f0, f0, f4, f11
	fmuls f4, f3, f1
	fmuls f10, f3, f2
	lfs f6, _94406c74bd2870f3_LCPI1_4@l(r3)
	lis r3, _94406c74bd2870f3_LCPI1_5@ha
	fmuls f0, f5, f0
	fmadds f10, f5, f1, f10
	fmadds f4, f5, f2, f4
	lfs f5, newTargetPosZ@l(r28)
	fmadds f0, f2, f1, f0
	lfs f7, _94406c74bd2870f3_LCPI1_5@l(r3)
	fmuls f1, f1, f1
	fmuls f2, f2, f2
	fmadds f1, f3, f3, f1
	fmadds f2, f3, f3, f2
	fadds f29, f0, f0
	fmadds f28, f1, f6, f9
	fnmadds f23, f1, f6, f9
	fmadds f1, f5, f5, f8
	fadds f31, f4, f4
	fmadds f30, f2, f6, f9
	fmuls f24, f10, f7
	fneg f22, f29
	bl _Z5sqrtff
	lis r3, newCamRotX@ha
	stfs f31, newCamRotX@l(r3)
	lis r3, distanceSetting@ha
	lfs f0, distanceSetting@l(r3)
	fmadds f3, f24, f1, f27
	lis r3, newCamRotY@ha
	fneg f2, f24
	stfs f3, newTargetPosX@l(r29)
	fmadds f3, f22, f1, f26
	fmadds f1, f23, f1, f25
	stfs f30, newCamRotY@l(r3)
	lis r3, newCamPosX@ha
	stfs f1, newTargetPosZ@l(r28)
	fmadds f1, f2, f0, f27
	lis r4, newCamPosY@ha
	lis r5, newCamPosZ@ha
	stfs f1, newCamPosX@l(r3)
	fmadds f1, f29, f0, f26
	fmadds f0, f28, f0, f25
	lis r3, newCamRotZ@ha
	stfs f3, newTargetPosY@l(r30)
	stfs f1, newCamPosY@l(r4)
	stfs f0, newCamPosZ@l(r5)
	stfs f29, newCamRotZ@l(r3)
	lfd f31, 120(r1)
	lfd f30, 112(r1)
	lfd f29, 104(r1)
	lfd f28, 96(r1)
	lfd f27, 88(r1)
	lfd f26, 80(r1)
	lfd f25, 72(r1)
	lfd f24, 64(r1)
	lfd f23, 56(r1)
	lfd f22, 48(r1)
	lfd f21, 40(r1)
	lfd f20, 32(r1)
	lfd f19, 24(r1)
	lwz r30, 16(r1)
	lwz r29, 12(r1)
	lwz r28, 8(r1)
	lwz r0, 132(r1)
	addi r1, r1, 128
	mtlr r0
	blr
_94406c74bd2870f3_LBB1_35:
	fcmpu cr7, f28, f29
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_34
	fcmpu cr7, f28, f31
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_34
	fcmpu cr7, f28, f30
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	or r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_34
	lis r3, _94406c74bd2870f3_LCPI1_0@ha
	lfs f0, _94406c74bd2870f3_LCPI1_0@l(r3)
	fsubs f1, f20, f21
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_40
	fneg f31, f31
_94406c74bd2870f3_LBB1_40:
	fadds f1, f24, f22
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_42
	fneg f30, f30
_94406c74bd2870f3_LBB1_42:
	fadds f1, f23, f19
	fcmpu cr7, f1, f0
	.int 0x7C600026 ; mfcr r3
	.int 0x7C800026 ; mfcr r4
	clrlwi	r3, r3, 31
	rlwinm r4, r4, 29, 31, 31
	xori r3, r3, 1
	xori r4, r4, 1
	and r3, r4, r3
	cmplwi	r3, 0
	bne	cr0, _94406c74bd2870f3_LBB1_34
	fneg f29, f29
	b _94406c74bd2870f3_LBB1_34
_94406c74bd2870f3_Lfunc_end1:

	.align 4
oldTargetPosX:
	.int	0x3efd6fdb

	.align 4
oldTargetPosY:
	.int	0x3e4cd218

	.align 4
oldTargetPosZ:
	.int	0x3f0cb1ee

	.align 4
oldCamPosX:
	.int	0x3a126197

	.align 4
oldCamPosY:
	.int	0x3b8418ff

	.align 4
oldCamPosZ:
	.int	0x3d039c01

	.align 4
headsetQuaternionX:
	.int	0x3d03d9a9

	.align 4
headsetQuaternionY:
	.int	0x3d1d9b1b

	.align 4
headsetQuaternionZ:
	.int	0x3d0d1c7e

	.align 4
headsetQuaternionW:
	.int	0x3eb26aef

	.align 4
headsetPositionX:
	.int	0x3e9fe5c9

	.align 4
headsetPositionY:
	.int	0x3f5930be

	.align 4
headsetPositionZ:
	.int	0x3f59359b

	.align 4
newTargetPosX:
	.int	0x00000000

	.align 4
newTargetPosY:
	.int	0x00000000

	.align 4
newTargetPosZ:
	.int	0x00000000

	.align 4
newCamPosX:
	.int	0x00000000

	.align 4
newCamPosY:
	.int	0x00000000

	.align 4
newCamPosZ:
	.int	0x00000000

	.align 4
newCamRotX:
	.int	0x00000000

	.align 4
newCamRotY:
	.int	0x00000000

	.align 4
newCamRotZ:
	.int	0x00000000

	.align 4
distanceSetting:
	.int	0x3f800000


; --- Address Patches ---
0x023F90E0 = nop
0x101E55F8 = .float 3.0
0x10416BF0 = .int 0x00000000
0x02E1905C = li r3, 0
