[AutoGenerated]
moduleMatches = 0x6267BFD0
.origin = codecave

_Z5sqrtff:
	stwu r1,-16(r1)
	stw r31,12(r1)
	mr r31,r1
	fdivs f12,f1,f1
	fadds f12,f1,f12
	lis r9,_94406c74bd2870f3_LC0@ha
	lfs f11,_94406c74bd2870f3_LC0@l(r9)
	fmuls f12,f12,f11
	fdivs f0,f1,f12
	fadds f12,f0,f12
	fmuls f12,f12,f11
	fdivs f0,f1,f12
	fadds f12,f0,f12
	fmuls f12,f12,f11
	fdivs f0,f1,f12
	fadds f12,f0,f12
	fmuls f12,f12,f11
	fdivs f0,f1,f12
	fadds f12,f0,f12
	fmuls f12,f12,f11
	fdivs f0,f1,f12
	fadds f12,f0,f12
	fmuls f0,f12,f11
	fdivs f1,f1,f0
	fadds f1,f1,f0
	fmuls f1,f1,f11
	addi r11,r31,16
	lwz r31,-4(r11)
	mr r1,r11
	blr
oldTargetPosX:
	.int	1056796635
oldTargetPosY:
	.int	1045221912
oldTargetPosZ:
	.int	1057796590
oldCamPosX:
	.int	974283159
oldCamPosY:
	.int	998512895
oldCamPosZ:
	.int	1023646721
headsetQuaternionX:
	.int	1023662505
headsetQuaternionY:
	.int	1025350427
headsetQuaternionZ:
	.int	1024269438
headsetQuaternionW:
	.int	1051880175
headsetPositionX:
	.int	1050666441
headsetPositionY:
	.int	1062809790
headsetPositionZ:
	.int	1062811035
newTargetPosX:
.uint 0
newTargetPosY:
.uint 0
newTargetPosZ:
.uint 0
newCamPosX:
.uint 0
newCamPosY:
.uint 0
newCamPosZ:
.uint 0
newCamRotX:
.uint 0
newCamRotY:
.uint 0
newCamRotZ:
.uint 0
distanceSetting:
	.int	1065353216
_Z20calculateNewRotationv:
	stwu r1,-128(r1)
	mflr r0
	stw r0,132(r1)
	stfd f19,24(r1)
	stfd f20,32(r1)
	stfd f21,40(r1)
	stfd f22,48(r1)
	stfd f23,56(r1)
	stfd f24,64(r1)
	stfd f25,72(r1)
	stfd f26,80(r1)
	stfd f27,88(r1)
	stfd f28,96(r1)
	stfd f29,104(r1)
	stfd f30,112(r1)
	stfd f31,120(r1)
	stw r28,8(r1)
	stw r29,12(r1)
	stw r30,16(r1)
	stw r31,20(r1)
	mr r31,r1
	lis r9,oldCamPosX@ha
	lfs f24,oldCamPosX@l(r9)
	lis r9,oldTargetPosX@ha
	lfs f22,oldTargetPosX@l(r9)
	fsubs f27,f22,f24
	lis r9,oldCamPosY@ha
	lfs f25,oldCamPosY@l(r9)
	lis r9,oldTargetPosY@ha
	lfs f23,oldTargetPosY@l(r9)
	fsubs f23,f23,f25
	lis r9,oldCamPosZ@ha
	lfs f26,oldCamPosZ@l(r9)
	lis r9,oldTargetPosZ@ha
	lfs f31,oldTargetPosZ@l(r9)
	fsubs f31,f31,f26
	fmuls f1,f27,f23
	fmuls f1,f1,f31
	bl _Z5sqrtff
	fdivs f22,f27,f1
	fdivs f23,f23,f1
	fdivs f31,f31,f1
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f30,_94406c74bd2870f3_LC4@l(r9)
	fmuls f0,f23,f30
	fmuls f28,f0,f31
	fmuls f29,f22,f23
	fmuls f1,f31,f29
	bl _Z5sqrtff
	fdivs f0,f28,f1
	fmuls f21,f31,f30
	fmuls f21,f21,f22
	fmuls f21,f21,f30
	fdivs f21,f21,f1
	fmuls f29,f29,f30
	fdivs f27,f29,f1
	fmuls f19,f23,f27
	fmuls f19,f19,f31
	fmuls f19,f19,f21
	fmuls f11,f31,f0
	fmuls f11,f11,f22
	fmuls f11,f11,f27
	fmuls f20,f22,f21
	fmuls f20,f20,f23
	fmuls f20,f20,f0
	fadds f12,f0,f11
	fadds f12,f12,f31
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f10,_94406c74bd2870f3_LC1@l(r9)
	fadds f12,f12,f10
	lis r9,_94406c74bd2870f3_LC3@ha
	lfs f1,_94406c74bd2870f3_LC3@l(r9)
	fmuls f12,f12,f1
	fsubs f29,f0,f11
	fsubs f29,f29,f31
	fadds f29,f29,f10
	fmuls f29,f29,f1
	fsubs f28,f11,f0
	fsubs f28,f28,f31
	fadds f28,f28,f10
	fmuls f28,f28,f1
	fneg f0,f0
	fsubs f0,f0,f11
	fadds f31,f0,f31
	fadds f31,f31,f10
	fmuls f31,f31,f1
	fcmpu cr7,f12,f30
	BNL cr7, _94406c74bd2870f3_L4
	fmr f12,f30
	.align 4
_94406c74bd2870f3_L4:
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f29,f0
	BNL cr7, _94406c74bd2870f3_L6
	fmr f29,f0
	.align 4
_94406c74bd2870f3_L6:
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f28,f0
	BNL cr7, _94406c74bd2870f3_L8
	fmr f28,f0
	.align 4
_94406c74bd2870f3_L8:
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f31,f0
	BNL cr7, _94406c74bd2870f3_L10
	fmr f31,f0
	.align 4
_94406c74bd2870f3_L10:
	fmr f1,f12
	bl _Z5sqrtff
	fmr f30,f1
	fmr f1,f29
	bl _Z5sqrtff
	fmr f29,f1
	fmr f1,f28
	bl _Z5sqrtff
	fmr f28,f1
	fmr f1,f31
	bl _Z5sqrtff
	fmr f31,f1
	fcmpu cr7,f30,f29
	cror 30,29,30
	BNE cr7, _94406c74bd2870f3_L12
	fcmpu cr7,f30,f28
	cror 30,29,30
	BNE cr7, _94406c74bd2870f3_L12
	fcmpu cr7,f30,f1
	cror 30,29,30
	BNE cr7, _94406c74bd2870f3_L12
	fsubs f23,f23,f20
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f23,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L40
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L16
	.align 4
_94406c74bd2870f3_L40:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L16:
	fmuls f29,f29,f0
	fsubs f27,f27,f22
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f27,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L41
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L17
	.align 4
_94406c74bd2870f3_L41:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L17:
	fmuls f28,f28,f0
	fsubs f21,f19,f21
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f21,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L42
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L18
	.align 4
_94406c74bd2870f3_L42:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L18:
	fmuls f31,f31,f0
	b _94406c74bd2870f3_L19
	.align 4
_94406c74bd2870f3_L12:
	fcmpu cr7,f30,f29
	cror 30,28,30
	BNE cr7, _94406c74bd2870f3_L20
	fcmpu cr7,f29,f28
	cror 30,29,30
	BNE cr7, _94406c74bd2870f3_L20
	fcmpu cr7,f29,f31
	cror 30,29,30
	BNE cr7, _94406c74bd2870f3_L20
	fsubs f23,f23,f20
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f23,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L43
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L24
	.align 4
_94406c74bd2870f3_L43:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L24:
	fmuls f30,f30,f0
	fadds f21,f21,f19
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f21,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L44
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L25
	.align 4
_94406c74bd2870f3_L44:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L25:
	fmuls f28,f28,f0
	fadds f27,f22,f27
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f27,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L45
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L26
	.align 4
_94406c74bd2870f3_L45:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L26:
	fmuls f31,f31,f0
	b _94406c74bd2870f3_L19
	.align 4
_94406c74bd2870f3_L20:
	fcmpu cr7,f30,f28
	cror 30,28,30
	BNE cr7, _94406c74bd2870f3_L27
	fcmpu cr7,f29,f28
	cror 30,28,30
	BNE cr7, _94406c74bd2870f3_L27
	fcmpu cr7,f28,f31
	cror 30,29,30
	BNE cr7, _94406c74bd2870f3_L27
	fsubs f27,f27,f22
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f27,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L46
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L31
	.align 4
_94406c74bd2870f3_L46:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L31:
	fmuls f30,f30,f0
	fadds f21,f21,f19
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f21,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L47
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L32
	.align 4
_94406c74bd2870f3_L47:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L32:
	fmuls f29,f29,f0
	fadds f23,f23,f20
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f23,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L48
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L33
	.align 4
_94406c74bd2870f3_L48:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L33:
	fmuls f31,f31,f0
	b _94406c74bd2870f3_L19
	.align 4
_94406c74bd2870f3_L27:
	fcmpu cr7,f30,f31
	cror 30,28,30
	BNE cr7, _94406c74bd2870f3_L19
	fcmpu cr7,f29,f31
	cror 30,28,30
	BNE cr7, _94406c74bd2870f3_L19
	fcmpu cr7,f28,f31
	cror 30,28,30
	BNE cr7, _94406c74bd2870f3_L19
	fsubs f21,f19,f21
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f21,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L49
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L37
	.align 4
_94406c74bd2870f3_L49:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L37:
	fmuls f30,f30,f0
	fadds f27,f22,f27
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f27,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L50
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L38
	.align 4
_94406c74bd2870f3_L50:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L38:
	fmuls f29,f29,f0
	fadds f23,f23,f20
	lis r9,_94406c74bd2870f3_LC4@ha
	lfs f0,_94406c74bd2870f3_LC4@l(r9)
	fcmpu cr7,f23,f0
	cror 30,29,30
	BEQ cr7, _94406c74bd2870f3_L51
	lis r9,_94406c74bd2870f3_LC2@ha
	lfs f0,_94406c74bd2870f3_LC2@l(r9)
	b _94406c74bd2870f3_L39
	.align 4
_94406c74bd2870f3_L51:
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f0,_94406c74bd2870f3_LC1@l(r9)
	.align 4
_94406c74bd2870f3_L39:
	fmuls f28,f28,f0
	.align 4
_94406c74bd2870f3_L19:
	fmuls f1,f30,f29
	fmuls f1,f1,f28
	fmuls f1,f1,f31
	bl _Z5sqrtff
	fdivs f30,f30,f1
	fdivs f6,f29,f1
	fdivs f28,f28,f1
	fdivs f1,f31,f1
	lis r9,headsetQuaternionW@ha
	lfs f10,headsetQuaternionW@l(r9)
	lis r9,headsetQuaternionZ@ha
	lfs f9,headsetQuaternionZ@l(r9)
	lis r9,headsetQuaternionY@ha
	lfs f8,headsetQuaternionY@l(r9)
	lis r9,headsetQuaternionX@ha
	lfs f11,headsetQuaternionX@l(r9)
	fmuls f22,f30,f10
	fmuls f7,f6,f9
	fadds f22,f22,f7
	fmuls f7,f28,f8
	fsubs f7,f22,f7
	fmuls f31,f1,f11
	fadds f22,f7,f31
	fneg f12,f30
	fmuls f23,f9,f12
	fmuls f0,f6,f10
	fadds f23,f23,f0
	fmuls f0,f28,f11
	fadds f0,f23,f0
	fmuls f23,f1,f8
	fadds f23,f0,f23
	fmuls f30,f30,f8
	fmuls f0,f6,f11
	fsubs f30,f30,f0
	fmuls f29,f28,f10
	fadds f30,f30,f29
	fmuls f0,f1,f9
	fadds f29,f30,f0
	fmuls f11,f11,f12
	fmuls f0,f6,f8
	fsubs f0,f11,f0
	fmuls f12,f28,f9
	fsubs f12,f0,f12
	fmuls f1,f1,f10
	fadds f31,f12,f1
	fmuls f30,f22,f22
	fmuls f0,f29,f31
	fmuls f27,f22,f23
	fsubs f27,f0,f27
	fadds f27,f27,f27
	fmuls f20,f23,f31
	fmuls f0,f22,f29
	fadds f20,f20,f0
	fadds f20,f20,f20
	fneg f20,f20
	fneg f19,f27
	fmuls f28,f31,f31
	fadds f28,f30,f28
	fadds f28,f28,f28
	lis r9,_94406c74bd2870f3_LC1@ha
	lfs f21,_94406c74bd2870f3_LC1@l(r9)
	fsubs f28,f28,f21
	fneg f28,f28
	lis r28,newTargetPosX@ha
	lfs f12,newTargetPosX@l(r28)
	lis r29,newTargetPosY@ha
	lfs f0,newTargetPosY@l(r29)
	lis r30,newTargetPosZ@ha
	lfs f1,newTargetPosZ@l(r30)
	fmuls f12,f12,f12
	fmuls f0,f0,f0
	fadds f0,f12,f0
	fmuls f1,f1,f1
	fadds f1,f0,f1
	bl _Z5sqrtff
	fmuls f0,f20,f1
	fadds f0,f24,f0
	stfs f0,newTargetPosX@l(r28)
	fmuls f0,f19,f1
	fadds f0,f25,f0
	stfs f0,newTargetPosY@l(r29)
	fmuls f1,f28,f1
	fadds f1,f26,f1
	stfs f1,newTargetPosZ@l(r30)
	lis r9,distanceSetting@ha
	lfs f0,distanceSetting@l(r9)
	fmuls f20,f20,f0
	fsubs f24,f24,f20
	lis r9,newCamPosX@ha
	stfs f24,newCamPosX@l(r9)
	fmuls f19,f19,f0
	fsubs f25,f25,f19
	lis r9,newCamPosY@ha
	stfs f25,newCamPosY@l(r9)
	fmuls f28,f28,f0
	fsubs f26,f26,f28
	lis r9,newCamPosZ@ha
	stfs f26,newCamPosZ@l(r9)
	fmuls f23,f23,f29
	fmuls f31,f22,f31
	fadds f31,f23,f31
	fadds f31,f31,f31
	lis r9,newCamRotX@ha
	stfs f31,newCamRotX@l(r9)
	fmuls f0,f29,f29
	fadds f30,f30,f0
	fadds f30,f30,f30
	fsubs f30,f30,f21
	lis r9,newCamRotY@ha
	stfs f30,newCamRotY@l(r9)
	lis r9,newCamRotZ@ha
	stfs f27,newCamRotZ@l(r9)
	addi r11,r31,128
	lwz r0,4(r11)
	mtlr r0
	lwz r28,-120(r11)
	lwz r29,-116(r11)
	lwz r30,-112(r11)
	lwz r31,-108(r11)
	lfd f19,-104(r11)
	lfd f20,-96(r11)
	lfd f21,-88(r11)
	lfd f22,-80(r11)
	lfd f23,-72(r11)
	lfd f24,-64(r11)
	lfd f25,-56(r11)
	lfd f26,-48(r11)
	lfd f27,-40(r11)
	lfd f28,-32(r11)
	lfd f29,-24(r11)
	lfd f30,-16(r11)
	lfd f31,-8(r11)
	mr r1,r11
	blr
_94406c74bd2870f3_LC0:
	.int	1056964608
_94406c74bd2870f3_LC1:
	.int	1065353216
_94406c74bd2870f3_LC2:
	.int	-1082130432
_94406c74bd2870f3_LC3:
	.int	1048576000
_94406c74bd2870f3_LC4:
	.int	0
