[AutoGenerated]
moduleMatches = 0x6267BFD0
.origin = codecave

	.align 4
_Z6ptrAddPvj:
_bac4eda9aae276e4_Lfunc_begin0:
	add r3, r3, r4
	blr
_bac4eda9aae276e4_Lfunc_end0:

	.align 4
_Z7readU32Pvj:
_bac4eda9aae276e4_Lfunc_begin1:
	mflr r0
	stwu r1, -16(r1)
	stw r0, 20(r1)
	bl _Z6ptrAddPvj
	lwz r3, 0(r3)
	lwz r0, 20(r1)
	addi r1, r1, 16
	mtlr r0
	blr
_bac4eda9aae276e4_Lfunc_end1:

	.align 4
_Z7readU16Pvj:
_bac4eda9aae276e4_Lfunc_begin2:
	mflr r0
	stwu r1, -16(r1)
	stw r0, 20(r1)
	bl _Z6ptrAddPvj
	lhz r3, 0(r3)
	lwz r0, 20(r1)
	addi r1, r1, 16
	mtlr r0
	blr
_bac4eda9aae276e4_Lfunc_end2:

	.align 4
_Z6readU8Pvj:
_bac4eda9aae276e4_Lfunc_begin3:
	mflr r0
	stwu r1, -16(r1)
	stw r0, 20(r1)
	bl _Z6ptrAddPvj
	lbz r3, 0(r3)
	lwz r0, 20(r1)
	addi r1, r1, 16
	mtlr r0
	blr
_bac4eda9aae276e4_Lfunc_end3:

	.align 4
_Z7readF32Pvj:
_bac4eda9aae276e4_Lfunc_begin4:
	mflr r0
	stwu r1, -16(r1)
	stw r0, 20(r1)
	bl _Z6ptrAddPvj
	lfs f1, 0(r3)
	lwz r0, 20(r1)
	addi r1, r1, 16
	mtlr r0
	blr
_bac4eda9aae276e4_Lfunc_end4:

	.align 4
instancingComputeSeed:
_bac4eda9aae276e4_Lfunc_begin5:
	mflr r0
	stwu r1, -16(r1)
	mr	r4, r3
	mulli r3, r3, 3
	stw r0, 20(r1)
	crxor 6, 6, 6
	stw r30, 8(r1)
	addi r30, r3, 2
	lis r3, _bac4eda9aae276e4_L__ModuleStringPool@ha
	addi r3, r3, _bac4eda9aae276e4_L__ModuleStringPool@l
	mr	r5, r30
	bl import.coreinit.OSReport
	mr	r3, r30
	lwz r30, 8(r1)
	lwz r0, 20(r1)
	addi r1, r1, 16
	mtlr r0
	blr
_bac4eda9aae276e4_Lfunc_end5:

	.align 4
hook_modelDraw:
_bac4eda9aae276e4_Lfunc_begin6:
	mflr r0
	stwu r1, -16(r1)
	stw r0, 20(r1)
	crxor 6, 6, 6
	stw r30, 8(r1)
	mr	r30, r4
	mr	r4, r3
	lis r3, _bac4eda9aae276e4_L__ModuleStringPool@ha
	addi r3, r3, _bac4eda9aae276e4_L__ModuleStringPool@l
	addi r3, r3, 54
	mr	r5, r30
	bl import.coreinit.OSReport
	cmplwi	r30, 0
	li r3, 2
	bc 12, eq, _bac4eda9aae276e4_LBB6_2
	ori r3, r30, 0
	b _bac4eda9aae276e4_LBB6_2
_bac4eda9aae276e4_LBB6_2:
	lwz r30, 8(r1)
	lwz r0, 20(r1)
	addi r1, r1, 16
	mtlr r0
	blr
_bac4eda9aae276e4_Lfunc_end6:

_bac4eda9aae276e4_ZL22gInstancingExampleName:
	.string	"stereo-instancing"

	.align 4
gInstancingInstanceCount:
	.int	2

_bac4eda9aae276e4_L__ModuleStringPool:
	.string	"[Instancing] instancingComputeSeed seed=%d result=%d\n"
	.string	"[Instancing] hook_modelDraw ctx=%08X instanceCount=%d\n"

