#include "CompilerDriver.h"

std::vector<std::filesystem::path> collectCompilableSourceFiles(
    const std::filesystem::path &path) {
  std::vector<std::filesystem::path> sourceFiles;
  std::error_code ec;
  for (auto &p : std::filesystem::recursive_directory_iterator(path, ec)) {
    auto &entryPath = p.path();
    if (!entryPath.has_extension())
      continue;
    auto ext = entryPath.extension();
    if (ext != ".cpp" && ext != ".c" && ext != ".cc" && ext != ".cxx")
      continue;
    sourceFiles.push_back(entryPath);
  }

  std::sort(sourceFiles.begin(), sourceFiles.end(),
            [](const auto &lhs, const auto &rhs) {
              return lhs.generic_string() < rhs.generic_string();
            });
  return sourceFiles;
}

std::filesystem::path getRelativeSourcePath(
    const std::filesystem::path &sourceRoot,
    const std::filesystem::path &sourceFilePath) {
  auto relativePath = sourceFilePath.lexically_relative(sourceRoot);
  if (relativePath.empty())
    return sourceFilePath.filename();
  return relativePath;
}

std::string getModuleIdentifier(
    const std::filesystem::path &sourceRoot,
    const std::filesystem::path &sourceFilePath) {
  return getRelativeSourcePath(sourceRoot, sourceFilePath).generic_string();
}

std::string sanitizeModuleGroupName(std::string_view name) {
  std::string result;
  result.reserve(name.size());

  bool previousWasUnderscore = false;
  for (char ch : name) {
    if (std::isalnum(static_cast<unsigned char>(ch))) {
      result.push_back(ch);
      previousWasUnderscore = false;
    } else if (!previousWasUnderscore) {
      result.push_back('_');
      previousWasUnderscore = true;
    }
  }

  while (!result.empty() && result.back() == '_')
    result.pop_back();

  if (result.empty())
    return "module";
  return result;
}

std::string getModuleGroupBaseName(
    const std::filesystem::path &sourceRoot,
    const std::filesystem::path &sourceFilePath,
    bool useSourceSpecificName) {
  if (!useSourceSpecificName)
    return "AutoGenerated";

  auto relativePath = getRelativeSourcePath(sourceRoot, sourceFilePath);
  relativePath.replace_extension();
  return std::format("AutoGenerated_{}",
                     sanitizeModuleGroupName(relativePath.generic_string()));
}

std::filesystem::path getMergedOutputFilePath(
    const std::filesystem::path &outputTarget) {
  if (outputTarget.has_extension())
    return outputTarget;
  return outputTarget / "patch_compiled.asm";
}

std::filesystem::path getSingleFileOutputPath(
    const std::filesystem::path &sourceFile,
    const std::filesystem::path &outputTarget, bool explicitOutputTarget) {
  if (!explicitOutputTarget)
    return sourceFile.parent_path() / "patch_compiled.asm";
  if (outputTarget.has_extension())
    return outputTarget;
  return outputTarget / "patch_compiled.asm";
}

std::optional<PreparedSourceModule> prepareSourceModule(
    const std::filesystem::path &sourceRoot,
    const std::filesystem::path &sourceFilePath,
    std::string_view moduleGroupName,
    std::optional<uint32_t> cliChecksumOverride,
    std::string &errorMessage) {
  auto sourceInput = loadSourceFileInput(sourceFilePath, errorMessage);
  if (!sourceInput) {
    return std::nullopt;
  }

  AssemblyConverter converter;
  if (!converter.prepareCppForLinking(
          sourceFilePath.string(), getModuleIdentifier(sourceRoot, sourceFilePath),
          sourceInput->compileContents)) {
    errorMessage = std::format("Compilation failed for '{}'.",
                               sourceFilePath.generic_string());
    return std::nullopt;
  }

  uint32_t finalChecksum = kDefaultModuleMatches;
  if (cliChecksumOverride) {
    finalChecksum = *cliChecksumOverride;
  } else if (sourceInput->hasExplicitChecksum) {
    finalChecksum = sourceInput->moduleMatches;
  } else if (auto found = findModuleMatchesInDirectory(sourceFilePath.parent_path())) {
    finalChecksum = *found;
  } else if (auto foundRoot = findModuleMatchesInDirectory(sourceRoot)) {
    finalChecksum = *foundRoot;
  } else {
    finalChecksum = kDefaultModuleMatches;
  }

  PreparedSourceModule preparedModule;
  preparedModule.sourceFilePath = sourceFilePath;
  preparedModule.moduleGroupName = std::string(moduleGroupName);
  preparedModule.moduleMatches = finalChecksum;
  preparedModule.converter = std::move(converter);
  return preparedModule;
}

bool resolveDiscardedExportedSymbols(
    const std::vector<PreparedSourceModule> &preparedModules,
    std::vector<std::set<std::string>> &discardedDefinitionsPerModule,
    std::string &errorMessage) {
  struct SymbolDefinitionSite {
    size_t moduleIndex = 0;
    ExportedSymbolLinkage linkage = ExportedSymbolLinkage::Strong;
  };

  std::map<std::string, std::vector<SymbolDefinitionSite>> symbolDefinitions;
  for (size_t moduleIndex = 0; moduleIndex < preparedModules.size();
       moduleIndex++) {
    for (const auto &[symbolName, linkage] :
         preparedModules[moduleIndex].converter.getDefinedExportedSymbols()) {
      symbolDefinitions[symbolName].push_back({moduleIndex, linkage});
    }
  }

  discardedDefinitionsPerModule.assign(preparedModules.size(), {});
  for (const auto &[symbolName, definitionSites] : symbolDefinitions) {
    std::vector<size_t> strongDefinitionModules;
    for (const auto &definitionSite : definitionSites) {
      if (definitionSite.linkage == ExportedSymbolLinkage::Strong) {
        strongDefinitionModules.push_back(definitionSite.moduleIndex);
      }
    }

    if (strongDefinitionModules.size() > 1) {
      errorMessage = std::format(
          "Symbol '{}' has multiple strong definitions in '{}' and '{}'.",
          symbolName,
          preparedModules[strongDefinitionModules[0]]
              .sourceFilePath.generic_string(),
          preparedModules[strongDefinitionModules[1]]
              .sourceFilePath.generic_string());
      return false;
    }

    size_t keptModuleIndex = definitionSites.front().moduleIndex;
    if (!strongDefinitionModules.empty()) {
      keptModuleIndex = strongDefinitionModules.front();
    }

    for (const auto &definitionSite : definitionSites) {
      if (definitionSite.moduleIndex != keptModuleIndex) {
        discardedDefinitionsPerModule[definitionSite.moduleIndex].emplace(
            symbolName);
      }
    }
  }

  return true;
}

bool processSourceFile(const std::filesystem::path &sourceFilePath,
                      const std::filesystem::path &outputFilePath,
                      std::optional<uint32_t> cliChecksumOverride) {
  std::string errorMessage;
  auto preparedModule = prepareSourceModule(
      sourceFilePath.parent_path(), sourceFilePath, "AutoGenerated",
      cliChecksumOverride, errorMessage);
  if (!preparedModule) {
    printf("Error: %s\n", errorMessage.c_str());
    return false;
  }

  printf("Target Checksum:  0x%08X\n", preparedModule->moduleMatches);
  printf("Output File:      %s\n", outputFilePath.generic_string().c_str());
  fflush(stdout);

  auto compiledPatch = preparedModule->converter.emitPatch(
      preparedModule->moduleGroupName, preparedModule->moduleMatches);
  util_writeFile(outputFilePath.string(), compiledPatch.get());
  return true;
}

bool processDirectory(const std::filesystem::path &path,
                     const std::filesystem::path &outputTarget,
                     std::optional<uint32_t> cliChecksumOverride) {
  auto sourceFiles = collectCompilableSourceFiles(path);
  if (sourceFiles.empty()) {
    printf("No source files (.cpp, .c, .cc, .cxx) found in %s\n",
           path.generic_string().c_str());
    return true;
  }

  auto outputFilePath = getMergedOutputFilePath(outputTarget);

  bool useSourceSpecificNames = sourceFiles.size() > 1;
  std::map<std::string, int> groupNameCounts;
  std::vector<PreparedSourceModule> preparedModules;
  preparedModules.reserve(sourceFiles.size());

  for (const auto &sourceFile : sourceFiles) {
    auto baseGroupName =
        getModuleGroupBaseName(path, sourceFile, useSourceSpecificNames);
    int groupCount = ++groupNameCounts[baseGroupName];
    std::string groupName =
        groupCount == 1 ? baseGroupName
                        : std::format("{}_{}", baseGroupName, groupCount);

    printf("Module Group:     %s\n", groupName.c_str());
    fflush(stdout);

    std::string errorMessage;
    auto preparedModule =
        prepareSourceModule(path, sourceFile, groupName, cliChecksumOverride, errorMessage);
    if (!preparedModule) {
      printf("Error: %s\n", errorMessage.c_str());
      return false;
    }
    preparedModules.emplace_back(std::move(*preparedModule));
  }

  if (!preparedModules.empty()) {
    printf("Target Checksum:  0x%08X\n", preparedModules.front().moduleMatches);
  }
  printf("Output File:      %s\n", outputFilePath.generic_string().c_str());
  fflush(stdout);

  std::string errorMessage;
  std::vector<std::set<std::string>> discardedDefinitionsPerModule;
  if (!resolveDiscardedExportedSymbols(preparedModules,
                                       discardedDefinitionsPerModule,
                                       errorMessage)) {
    printf("Error: %s\n", errorMessage.c_str());
    return false;
  }

  TextFile mergedOutput;
  for (size_t moduleIndex = 0; moduleIndex < preparedModules.size();
       moduleIndex++) {
    auto compiledPatch = preparedModules[moduleIndex].converter.emitPatch(
        preparedModules[moduleIndex].moduleGroupName,
        preparedModules[moduleIndex].moduleMatches,
        discardedDefinitionsPerModule[moduleIndex]);
    appendTextFile(mergedOutput, std::move(compiledPatch));
  }

  util_writeFile(outputFilePath.string(), &mergedOutput);
  return true;
}

bool compileSingleTarget(const std::filesystem::path &inputPath,
                         const std::filesystem::path &outputTarget,
                         std::optional<uint32_t> cliChecksum,
                         bool explicitOutputTarget) {
  std::error_code ec;
  if (!std::filesystem::exists(inputPath, ec)) {
    printf("Error: Input path does not exist: %s\n",
           inputPath.generic_string().c_str());
    return false;
  }

  if (std::filesystem::is_directory(inputPath, ec)) {
    return processDirectory(inputPath, outputTarget, cliChecksum);
  } else {
    auto outputFilePath =
        getSingleFileOutputPath(inputPath, outputTarget, explicitOutputTarget);
    return processSourceFile(inputPath, outputFilePath, cliChecksum);
  }
}
