#include "StringParser.h"
#include "common.h"

struct TextFile {
  std::vector<std::string> lines;
};

std::unique_ptr<TextFile> util_readTextFile(std::string_view path) {
  std::ifstream file(path.data(), std::ios::binary);
  if (!file.is_open()) {
    __debugbreak();
  }

  auto textFile = std::make_unique<TextFile>();
  std::string line;
  while (std::getline(file, line)) {
    // Remove trailing '\r' if present (CRLF format)
    if (!line.empty() && line.back() == '\r') {
      line.pop_back();
    }
    // Remove leading '\r' if present
    if (!line.empty() && line.front() == '\r') {
      line.erase(line.begin());
    }
    textFile->lines.push_back(std::move(line));
  }
  return textFile;
}

void util_writeFile(std::string_view path, const TextFile *textFile) {
  std::filesystem::path p(path);
  std::error_code ec;
  std::filesystem::create_directories(p.parent_path(), ec);

  std::ofstream file(path.data(), std::ios::binary);
  if (!file.is_open()) {
    __debugbreak();
  }

  for (const auto &line : textFile->lines) {
    file.write(line.data(), line.size());
    file.put('\n');
  }
}

bool util_stringReplace(std::string &str, const std::string &from,
                        const std::string &to) {
  size_t start_pos = str.find(from);
  if (start_pos == std::string::npos)
    return false;
  str.replace(start_pos, from.length(), to);
  return true;
}

std::string AsmUpdater_fixInstruction(std::string_view instructionText);
std::string AsmUpdater_changeRegisterSyntax(std::string &instructionText);
std::string AsmUpdater_fixDotLabels(uint64_t unitHash,
                                    std::string instructionText);

class AssemblyConverter {
public:
  AssemblyConverter() = default;

  const TextFile *getOutput() const { return m_outputTextFile.get(); }

  void start() {
    m_outputTextFile = std::make_unique<TextFile>();
    m_outputTextFile->lines.emplace_back("[AutoGenerated]");
    m_outputTextFile->lines.emplace_back("moduleMatches = 0x6267BFD0");
    m_outputTextFile->lines.emplace_back(".origin = codecave");
    m_outputTextFile->lines.emplace_back("");
  }

  void compileCpp(std::string_view sourceFilePath,
                  std::string_view outputFilePath) {
    std::filesystem::path sourcePath(sourceFilePath);
    printf("Compiling %s...\n", sourcePath.filename().string().c_str());
    SECURITY_ATTRIBUTES saAttr;

    HANDLE g_hChildStd_IN_Rd = NULL;
    HANDLE g_hChildStd_IN_Wr = NULL;

    saAttr.nLength = sizeof(SECURITY_ATTRIBUTES);
    saAttr.bInheritHandle = TRUE;
    saAttr.lpSecurityDescriptor = NULL;

    if (!CreatePipe(&g_hChildStd_IN_Rd, &g_hChildStd_IN_Wr, &saAttr, 0))
      __debugbreak();
    if (!SetHandleInformation(g_hChildStd_IN_Wr, HANDLE_FLAG_INHERIT, 0))
      __debugbreak();

    std::string ext = sourcePath.extension().string();
    bool forceCpp = (ext == ".c" || ext == ".h");

    // create the process
    std::string cmdline;
    if (g_compilerMode == CompilerMode::Clang) {
      cmdline.append(g_clangPath);
      cmdline.append(
          " -target ppc32 -mno-crbits -ffreestanding -fno-autolink "
          "-fno-data-sections -fno-function-sections -fno-exceptions");
      cmdline.append(
          " -fno-verbose-asm -fno-rtti -fbasic-block-sections=none -O1 "
          "-fvisibility=default -femit-all-decls -fno-inline -std=c++17");
      cmdline.append(
          " -mllvm -ppc-asm-full-reg-names -mllvm -disable-ppc-cmp-opt -mllvm "
          "-enable-ppc-branch-coalesce ");
      if (forceCpp)
        cmdline.append(" -x c++");
      cmdline.append(" -S \"");
      cmdline.append(sourceFilePath);
      cmdline.append("\"");
      cmdline.append(" --output \"");
      cmdline.append(outputFilePath);
      cmdline.append("\"");
    } else if (g_compilerMode == CompilerMode::GCC) {
      cmdline.append(g_gccPath);
      cmdline.append(" -emit-llvm -O2 -mcpu=750 -mbig-endian -m32 -fno-rtti "
                     "-fno-ident -fno-toplevel-reorder -mregnames "
                     "-fno-function-sections -ffreestanding");
      cmdline.append(
          " -fno-data-sections -msdata=none -mno-sdata -fno-exceptions "
          "-fno-omit-frame-pointer -fno-asynchronous-unwind-tables");
      cmdline.append(" -mno-powerpc-gpopt -mcall-eabi");
      cmdline.append(" -falign-functions=4 -falign-labels=4 -falign-jumps=0 "
                     "-falign-loops=0 -std=c++11");
      if (forceCpp)
        cmdline.append(" -x c++");
      cmdline.append(" -S \"");
      cmdline.append(sourceFilePath);
      cmdline.append("\"");
      cmdline.append(" --output \"");
      cmdline.append(outputFilePath);
      cmdline.append("\"");
    } else {
      printf("Error: No compiler found! Please install GCC or Clang.\n");
      ExitProcess(1);
    }

    printf("Executing command: %s\n", cmdline.c_str());
    fflush(stdout);

    PROCESS_INFORMATION piProcInfo;
    STARTUPINFOA siStartInfo;
    BOOL bSuccess = FALSE;
    ZeroMemory(&piProcInfo, sizeof(PROCESS_INFORMATION));
    ZeroMemory(&siStartInfo, sizeof(STARTUPINFO));
    siStartInfo.cb = sizeof(STARTUPINFO);
    siStartInfo.hStdError = GetStdHandle(STD_OUTPUT_HANDLE);
    siStartInfo.hStdOutput = GetStdHandle(STD_OUTPUT_HANDLE);
    siStartInfo.hStdInput = g_hChildStd_IN_Rd;
    siStartInfo.dwFlags |= STARTF_USESTDHANDLES;

    bSuccess = CreateProcessA(NULL,
                              (LPSTR)cmdline.c_str(), // command line
                              NULL, // process security attributes
                              NULL, // primary thread security attributes
                              TRUE, // handles are inherited
                              0,    // creation flags
                              NULL, // use parent's environment
                              NULL, // use parent's current directory
                              &siStartInfo, // STARTUPINFO pointer
                              &piProcInfo); // receives PROCESS_INFORMATION

    if (!bSuccess) {
      printf("CreateProcessA failed! Error: %d\n", GetLastError());
      fflush(stdout);
      __debugbreak();
    } else {
      CloseHandle(piProcInfo.hThread);
      CloseHandle(g_hChildStd_IN_Wr);
    }

    // wait for return code
    WaitForSingleObject(piProcInfo.hProcess, INFINITE);
    DWORD exitCode;
    if (GetExitCodeProcess(piProcInfo.hProcess, &exitCode) == FALSE) {
      __debugbreak();
    }
    CloseHandle(piProcInfo.hProcess);
    printf("Command exited with code: %d\n", exitCode);
    fflush(stdout);
    if (exitCode != 0) {
      Sleep(1000 * 3);
      ExitProcess(exitCode);
    }
  }

  void convertClangToCemu(std::string_view moduleName,
                          const TextFile &inputFile, TextFile &outputTextFile) {
    printf("Starting convertClangToCemu for module %s...\n",
           std::string(moduleName).c_str());
    fflush(stdout);

    // calc hash
    uint64_t unitHash = 0;
    for (uint32_t t = 0; t < 8; t++) {
      for (auto &itr : moduleName) {
        unitHash += (uint64_t)itr;
        unitHash = _rotr64(unitHash, 3);
      }
    }

    for (auto inputLine : inputFile.lines) {
      StringTokenParser parser(inputLine.data(), (int32_t)inputLine.size());
      // check for directives that we can skip
      parser.skipWhitespaces();
      if (parser.matchWordI(".text") || parser.matchWordI(".file") ||
          parser.matchWordI(".globl") || parser.matchWordI(".type") ||
          parser.matchWordI(".size") || parser.matchWordI(".section") ||
          parser.matchWordI(".weak") || parser.matchWordI(".data") ||
          parser.matchWordI(".ident") || parser.matchWordI(".addrsig") ||
          parser.matchWordI(".addrsig_sym") || parser.matchWordI(".machine")) {
        continue;
      }
      if (g_compilerMode == CompilerMode::GCC) {
        if (parser.matchWordI(".align 2"))
          continue;
        if (parser.matchWordI(".gnu_attribute"))
          continue;
        if (parser.matchWordI(".lcomm")) {
          // translate this to a data variable
          const char *symbolName;
          int32_t symbolNameLen;
          if (!parser.parseSymbolName(symbolName, symbolNameLen))
            __debugbreak();
          std::string_view svSymbolName(symbolName, symbolNameLen);
          parser.skipWhitespaces();
          if (!parser.compareCharacter(0, ','))
            __debugbreak();
          parser.skipCharacters(1);
          const char *lenFieldName;
          int32_t lenFieldNameLen;
          if (!parser.parseSymbolName(lenFieldName, lenFieldNameLen))
            __debugbreak();

          parser.skipWhitespaces();
          if (parser.compareCharacter(0, ','))
          {
            parser.skipCharacters(1);
            const char* alignFieldName;
            int32_t alignFieldNameLen;
            parser.parseSymbolName(alignFieldName, alignFieldNameLen);
          }

          std::string_view svFieldLen(lenFieldName, lenFieldNameLen);
          outputTextFile.lines.emplace_back(std::format("{}:", svSymbolName));
          int lcommLen = std::atoi(std::string(svFieldLen).c_str());
          if ((lcommLen % 4) != 0) {
            printf("lcomm unaligned. Padding to multiple of 4. Unsure if this "
                   "is ok\n");
            while ((lcommLen % 4) != 0)
              lcommLen++;
          }
          int numWords = lcommLen / 4;
          if (numWords <= 0)
            __debugbreak();
          outputTextFile.lines.emplace_back(".uint 0");
          for (int i = 1; i < numWords; i++) {
            outputTextFile.lines.back().append(",0");
          }
          continue;
        }

        inputLine = AsmUpdater_changeRegisterSyntax(inputLine);
        inputLine = AsmUpdater_fixDotLabels(
            unitHash,
            inputLine); // this one could potentially be used for clang too
        parser = StringTokenParser(inputLine.data(), (int32_t)inputLine.size());
      }

      // some commands have to be translated
      if (parser.matchWordI(".p2align")) {
        uint32_t val;
        if (!parser.parseU32(val))
          __debugbreak();
        outputTextFile.lines.emplace_back(std::format("\t.align {}", 1 << val));
        continue;
      }
      if (parser.matchWordI(".string")) {
        // append an extra .align 4 after the string
        // GCC assembly seems to imply it
        outputTextFile.lines.emplace_back(inputLine);
        outputTextFile.lines.emplace_back("\t.align 4");
        continue;
      }
      if (parser.matchWordI(".zero")) {
        uint32_t zeroSize;
        if (!parser.parseU32(zeroSize))
          __debugbreak();
        if (zeroSize > 0) {
          uint32_t numInts = zeroSize / 4;
          uint32_t remainder = zeroSize % 4;
          if (numInts > 0) {
            std::string line = "\t.int 0";
            for (uint32_t i = 1; i < numInts; i++)
              line.append(",0");
            outputTextFile.lines.emplace_back(std::move(line));
          }
          if (remainder >= 2) {
            outputTextFile.lines.emplace_back("\t.short 0");
            remainder -= 2;
          }
          if (remainder == 1) {
            outputTextFile.lines.emplace_back("\t.byte 0");
          }
        }
        continue;
      }
      // and some instructions also need their syntax adjusted
      parser.skipWhitespaces();
      if (!parser.compareCharacter(0, '.')) {
        // dissect instructions into
        inputLine = AsmUpdater_fixInstruction(inputLine);
      } else {
        // .asciz -> .string
        util_stringReplace(inputLine, ".asciz", ".string");
        // .long -> .int
        util_stringReplace(inputLine, ".long", ".int");
      }

      util_stringReplace(inputLine, ".Lfunc_", "__Lfunc_");
      util_stringReplace(inputLine, ".LBB", "__LBB");

      // import directives
      util_stringReplace(inputLine, "_IMPORT_GX2_", "import.gx2.");
      util_stringReplace(inputLine, "_IMPORT_COREINIT_", "import.coreinit.");

      outputTextFile.lines.emplace_back(inputLine);
    }
  }

  void findLabels(const TextFile &inputFile) {
    printf("Starting findLabels for %d lines...\n",
           (int)inputFile.lines.size());
    fflush(stdout);
    for (const auto &line : inputFile.lines) {
      std::string_view p = line;

      // trim whitespaces
      while (!p.empty() && (p.front() == ' ' || p.front() == '\t'))
        p.remove_prefix(1);
      while (!p.empty() && (p.back() == ' ' || p.back() == '\t'))
        p.remove_suffix(1);

      // cut off comments
      size_t commentPos = p.find('#');
      if (commentPos != std::string_view::npos)
        p = p.substr(0, commentPos);

      // trim whitespaces again
      while (!p.empty() && (p.front() == ' ' || p.front() == '\t'))
        p.remove_prefix(1);
      while (!p.empty() && (p.back() == ' ' || p.back() == '\t'))
        p.remove_suffix(1);

      if (p.empty())
        continue;

      // check if line ends with ':' indicating a label
      if (p.back() == ':') {
        std::string_view label = p.substr(0, p.size() - 1);
        printf("%s\n", std::string(label).c_str());
      }
    }
  }

  void translateClangAssembly(std::string_view path,
                              std::string_view moduleName) {
    auto inputFile = util_readTextFile(path);
    findLabels(*inputFile);
    convertClangToCemu(moduleName, *inputFile, *m_outputTextFile);
  }

private:
  std::unique_ptr<TextFile> m_outputTextFile;
};

void processDirectory(std::string_view path, std::string_view outputPatchFile) {
  AssemblyConverter converter;
  converter.start();

  std::string clangAssemblyFilePath;
  clangAssemblyFilePath.append(path);
  if (!clangAssemblyFilePath.empty() && clangAssemblyFilePath.back() != '/' &&
      clangAssemblyFilePath.back() != '\\') {
    clangAssemblyFilePath.append("/");
  }
  clangAssemblyFilePath.append("temp_asm.s");

  int compiledCount = 0;
  std::error_code ec;
  for (auto &p : std::filesystem::recursive_directory_iterator(path, ec)) {
    auto &entryPath = p.path();
    if (!entryPath.has_extension())
      continue;
    auto ext = entryPath.extension();
    if (ext != ".cpp" && ext != ".c" && ext != ".cc" && ext != ".cxx")
      continue;
    if (entryPath.filename() == "temp_asm.s")
      continue;

    converter.compileCpp(entryPath.string(), clangAssemblyFilePath);
    converter.translateClangAssembly(clangAssemblyFilePath,
                                     entryPath.filename().generic_string());
    compiledCount++;
  }

  if (compiledCount > 0) {
    util_writeFile(outputPatchFile, converter.getOutput());
  } else {
    printf("No source files (.cpp, .c, .cc, .cxx) found in %s\n",
           std::string(path).c_str());
  }

  // Delete temporary file
  std::filesystem::remove(clangAssemblyFilePath, ec);
}

int main(int argc, char *argv[]) {
  std::filesystem::path exeDir = getExecutableDir();
  std::filesystem::path configPath = "";

  // Check if config.ini exists in current directory or next to executable
  if (std::filesystem::exists("config.ini")) {
    configPath = "config.ini";
  } else if (std::filesystem::exists(exeDir / "config.ini")) {
    configPath = exeDir / "config.ini";
  }

  Config config;
  std::filesystem::path configDir = exeDir;
  if (!configPath.empty()) {
    config = parseIniFile(configPath);
    configDir = configPath.parent_path();
  }

  detectCompiler(configDir, config);

  std::filesystem::path sourceDir = "";
  std::filesystem::path outFile = "";

  if (argc > 1) {
    // Drag & drop or CLI arguments
    std::filesystem::path argPath(argv[1]);
    if (std::filesystem::is_directory(argPath)) {
      sourceDir = argPath;
      outFile = argPath / "patch_compiled.asm";
    } else {
      sourceDir = argPath.parent_path();
      outFile = sourceDir / "patch_compiled.asm";
    }

    if (argc > 2) {
      outFile = argv[2];
    }
  } else {
    // Check CWD for C/C++ source files
    bool hasSourceFilesCwd = false;
    std::error_code ec;
    for (const auto &entry : std::filesystem::directory_iterator(".", ec)) {
      if (entry.is_regular_file()) {
        auto ext = entry.path().extension();
        if (ext == ".cpp" || ext == ".c" || ext == ".cc" || ext == ".cxx") {
          hasSourceFilesCwd = true;
          break;
        }
      }
    }

    if (hasSourceFilesCwd) {
      sourceDir = ".";
      outFile = "./patch_compiled.asm";
    } else {
      // Load paths from config.ini
      if (configPath.empty()) {
        configPath = exeDir / "config.ini";
        writeDefaultIniFile(configPath);
        config = parseIniFile(configPath);
        configDir = configPath.parent_path();
        detectCompiler(configDir, config);
      }

      std::string srcDirStr =
          config.get("Paths", "SourceDir", "examples/camera");
      std::string outValStr =
          config.get("Paths", "OutFile", "examples/camera/patch_compiled.asm");

      sourceDir = resolvePath(configDir, srcDirStr);
      outFile = resolvePath(configDir, outValStr);
    }
  }

  printf("Source Directory: %s\n", sourceDir.generic_string().c_str());
  printf("Output File:      %s\n", outFile.generic_string().c_str());

  std::error_code ec;
  if (std::filesystem::exists(sourceDir, ec)) {
    processDirectory(sourceDir.string(), outFile.string());
  } else {
    printf("Error: Source directory does not exist: %s\n",
           sourceDir.generic_string().c_str());
  }

  printf("done\n");
  for (int i = 0; i < 3; i++)
    Sleep(1000);

  return 0;
}