name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2025-vs2026
    env:
      VCPKG_INSTALLATION_ROOT: C:\vcpkg
      VCPKG_DOWNLOADS: ${{ github.workspace }}/vcpkg-downloads

    steps:
      - uses: actions/checkout@v7

      - name: Cache vcpkg_installed
        uses: actions/cache@v4
        id: cache-vpkg
        with:
          path: |
            vcpkg_installed
            vcpkg-downloads
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

      - name: Configure CMake
        run: >
          cmake -B build -S . 
          -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake" 
          -DVCPKG_TARGET_TRIPLET=x64-windows-static

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: CemuPatchCompiler-Release
          path: build/Release/CemuPatchCompiler-release.exe


