name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@v7

      - name: Download Precompiled LLVM
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download dependencies-v1 --repo ${{ github.repository }} --pattern "llvm-release-libs.tar.xz"

      - name: Extract LLVM
        run: |
          mkdir llvm-precompiled
          tar -xf llvm-release-libs.tar.xz -C llvm-precompiled

      - name: Patch LLVM CMake Exports
        shell: pwsh
        run: |
          Get-ChildItem -Path llvm-precompiled -Filter *.cmake -Recurse | ForEach-Object {
            (Get-Content $_.FullName) -replace 'FATAL_ERROR', 'STATUS' | Set-Content $_.FullName
          }

      - name: Create Visual Studio Directory Junction
        shell: pwsh
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          Write-Host "Detected Visual Studio at: $vsPath"
          $targetPath = "C:\Program Files\Microsoft Visual Studio\18\Community"
          if (-not (Test-Path $targetPath)) {
            $parentDir = Split-Path -Path $targetPath -Parent
            if (-not (Test-Path $parentDir)) {
              New-Item -ItemType Directory -Path $parentDir -Force
            }
            New-Item -ItemType Junction -Path $targetPath -Value $vsPath -Force
            Write-Host "Created junction from $targetPath to $vsPath"
          }

      - name: Configure CMake
        run: >
          cmake -B build -S . 
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/llvm-precompiled"

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: CemuPatchCompiler-Release
          path: build/Release/CemuPatchCompiler-release.exe
